# Standardized Model Configuration File
# This file contains all tunable parameters for the Adaptive Loss Architecture models

# Model Architecture Parameters
model:
  # Neural Network Architecture
  hidden_size: 128
  dropout_rates:
    layer1: 0.3
    layer2: 0.2
    layer3: 0.1
  
  # Network depth configuration
  hidden_layers:
    - size: 128  # First hidden layer
      dropout: 0.3
    - size: 64   # Second hidden layer (hidden_size // 2)
      dropout: 0.2
    - size: 32   # Third hidden layer (hidden_size // 4)
      dropout: 0.1

# Training Parameters
training:
  epochs: 150
  batch_size: 64
  learning_rate: 0.001
  weight_decay: 0.00001
  shuffle: false  # Keep false for time series data
  
  # Progress reporting
  progress_report_interval: 25  # Report every N epochs
  
  # Early stopping (optional)
  early_stopping:
    enabled: false
    patience: 20
    min_delta: 1e-6

# Adaptive Loss Function Parameters
adaptive_loss:
  # Weight constraints
  min_weight: 0.001
  max_weight: 0.5
  learning_rate_factor: 0.1
  
  # Weight update frequency
  weight_update_interval: 10  # Update weights every N epochs
  weight_update_adjustment: 0.1  # Adjustment factor for weight updates
  
  # Penalty weights (ablation study flags)
  penalties:
    temporal:
      enabled: false
      weight: 0.01
    volatility:
      enabled: false
      weight: 0.01
    smoothness:
      enabled: false
      weight: 0.01
    momentum:
      enabled: true
      weight: 0.01
  
  # Feature category base weights
  category_base_weights:
    trend: 0.12
    momentum: 0.10
    volume: 0.08
    volatility: 0.06
    signal: 0.15
    other: 0.05

# Data Processing Parameters
data_processing:
  # Data fetching
  days_lookback: 365
  target_horizon: 1
  test_size: 0.2
  
  # Feature engineering
  lag_periods: [1, 2, 3]
  max_features: 15
  enforce_diversity: true
  
  # Missing value handling
  imputation_strategy: "median"  # median, mean, most_frequent
  max_nan_threshold: 0.7  # Remove features with >70% NaN values
  
  # Scaling
  feature_scaler: "robust"  # robust, standard, minmax
  target_scaler: "standard"  # standard, robust, minmax

# Unified Target Configuration
unified_targets:
  # Primary target for all models
  primary_target: "returns"  # returns, prices, volatility, direction
  
  # Secondary targets to also compute
  secondary_targets: ["prices", "direction"]
  
  # Target horizon (must match data_processing.target_horizon)
  target_horizon: 1
  
  # Returns calculation method
  returns_type: "log_returns"  # log_returns, simple_returns, pct_change
  
  # Volatility target parameters
  volatility_window: 20
  
  # Direction target parameters
  direction_threshold: 0.001  # Minimum price change to consider as directional move
  
  # Scaling preferences for different targets
  price_scaling: "standard"  # standard, robust, minmax
  
  # Validation settings
  validation_enabled: true
  
  # Target-specific metrics
  target_metrics:
    returns:
      primary: "mae"
      secondary: ["mse", "directional_accuracy", "bias", "sharpe_ratio"]
    prices:
      primary: "mae"
      secondary: ["mse", "mape", "bias"]
    volatility:
      primary: "mae"
      secondary: ["mse", "directional_accuracy"]
    direction:
      primary: "accuracy"
      secondary: ["precision", "recall", "f1"]
  
  # Model-specific target configurations
  model_configs:
    adaptive:
      focus_target: "target_returns"
      loss_function_target: "returns"
      primary_metrics: ["mae", "directional_accuracy", "bias"]
    comparison:
      comparison_targets: ["target_returns", "target_prices"]
      comparison_metrics: ["mae", "mse", "directional_accuracy", "bias"]
    evaluation:
      evaluation_targets: ["target_returns", "target_prices", "target_direction"]
      comprehensive_metrics: true

# Feature Selection Parameters
feature_selection:
  # Selection strategy
  max_features: 15
  enforce_category_diversity: true
  min_per_category: 1  # Minimum features per category when enforcing diversity
  
  # Category diversity weights
  max_per_category: 3  # Maximum features per category (when not enforcing diversity)
  high_correlation_threshold: 0.7  # Include high correlation features regardless of category limits
  
  # Feature categories and keywords
  categories:
    trend:
      keywords: ['sma', 'ema', 'ma_', 'bb_middle', 'vwap', 'psar']
      priority: 1
    momentum:
      keywords: ['rsi', 'stoch', 'williams', 'cci', 'mfi', 'momentum', 'roc']
      priority: 2
    volume:
      keywords: ['volume', 'obv', 'adl']
      priority: 3
    volatility:
      keywords: ['atr', 'volatility', 'bb_width', 'bb_upper', 'bb_lower']
      priority: 4
    signal:
      keywords: ['macd', 'bb_position']
      priority: 1
    other:
      keywords: []
      priority: 5

# Technical Indicators Parameters
technical_indicators:
  # Moving Averages
  sma_periods: [5, 10, 20, 50, 200]
  ema_periods: [12, 26, 50]
  
  # Momentum Indicators
  rsi_period: 14
  stochastic_period: 14
  williams_r_period: 14
  cci_period: 20
  momentum_period: 10
  roc_period: 12
  
  # Bollinger Bands
  bb_period: 20
  bb_std_dev: 2
  
  # MACD
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  
  # Volume Indicators
  mfi_period: 14
  
  # Volatility
  atr_period: 14
  volatility_period: 20
  
  # Support/Resistance
  support_resistance_period: 20
  
  # Advanced Volatility
  volatility_lookback: 20
  stability_threshold: 0.02  # Coefficient of variation threshold for stability

# Evaluation Parameters
evaluation:
  # Metrics to calculate
  metrics:
    - "mae"
    - "mse" 
    - "rmse"
    - "bias"
    - "directional_accuracy"
    - "bias_corrected_mae"
    - "sharpe_ratio"
    - "max_drawdown"
    - "hit_rate"
  
  # Bias correction
  bias_correction: true
  
  # Directional accuracy calculation
  directional_accuracy: true
  
  # Statistical rigor parameters
  statistical_testing:
    enabled: true
    significance_level: 0.05
    tests: ["wilcoxon", "t_test", "bootstrap"]
    bootstrap_samples: 1000
  
  # Cross-validation for robust evaluation
  cross_validation:
    enabled: true
    method: "time_series_split"  # time_series_split, walk_forward
    n_splits: 5
    test_size_ratio: 0.2
    gap: 0  # Gap between train and test to prevent leakage
  
  # Multiple runs for statistical robustness
  multiple_runs:
    enabled: true
    n_runs: 10  # Number of independent runs
    aggregate_method: "mean"  # mean, median
    report_confidence_intervals: true
    confidence_level: 0.95

# Optimization Parameters (for hyperparameter tuning)
optimization:
  # Parameter search spaces
  search_spaces:
    learning_rate: [0.0001, 0.001, 0.01]
    hidden_size: [64, 128, 256]
    batch_size: [32, 64, 128]
    epochs: [100, 150, 200]
    dropout_rates:
      layer1: [0.2, 0.3, 0.4]
      layer2: [0.1, 0.2, 0.3]
      layer3: [0.05, 0.1, 0.15]
  
  # Optimization strategy
  strategy: "grid_search"  # grid_search, random_search, bayesian
  cv_folds: 3
  scoring_metric: "mae"

# Logging and Output Parameters
logging:
  # Console output
  verbose: true
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  
  # Progress tracking
  show_progress_bar: true
  log_training_progress: true
  log_weight_updates: true
  
  # File output
  save_results: true
  results_dir: "results"
  save_plots: true
  plots_dir: "plots"

# Experimental Parameters (for research and ablation studies)
experimental:
  # Ablation study flags
  ablation_study:
    enabled: false
    components_to_ablate: ["temporal_penalty", "volatility_penalty", "smoothness_penalty"]
  
  # Model comparison
  compare_with_baseline: true
  baseline_model: "standard_mse"
  
  # Advanced features
  use_advanced_volatility: true
  use_lagged_features: true
  
  # Research modes
  research_mode: false  # Enables additional experimental features
  debug_mode: false     # Enables detailed debugging output

# Environment Parameters
environment:
  # Computational resources
  device: "auto"  # auto, cpu, cuda
  num_workers: 4  # For data loading
  
  # Random seeds for reproducibility
  random_seed: 42
  torch_seed: 42
  numpy_seed: 42
  
  # Memory management
  pin_memory: true
  persistent_workers: false

# API and Data Source Parameters
data_sources:
  # Primary data source
  primary_source: "schwab_api"
  
  # API configuration
  schwab_api:
    period_type: "year"
    period: 1
    frequency_type: "daily"
    frequency: 1
    extended_hours: false
  
  # Fallback options
  fallback_sources: ["local_csv", "yahoo_finance"]
  
  # Data validation
  min_data_points: 50
  validate_data_quality: true

# Model Persistence Parameters
persistence:
  # Model saving
  save_models: true
  model_save_dir: "saved_models"
  save_best_only: true
  
  # Checkpoint saving
  save_checkpoints: false
  checkpoint_interval: 50  # Save every N epochs
  
  # Model loading
  load_pretrained: false
  pretrained_model_path: null
  
  # Export formats
  export_formats: ["pytorch", "onnx"]  # pytorch, onnx, torchscript
